"use client";
import { useEffect, useMemo, useRef, useState } from 'react';
import { Copy, Plus, RefreshCw } from 'lucide-react';
import type { EventView, Person } from '@/lib/boda-service/types';
import { downloadFile } from './client';
import { PersonSupportFields, accessibilityLabels } from './PersonSupportFields';
import styles from './studio.module.css';
export type Mutate = (action:string, payload?:Record<string,unknown>)=>Promise<boolean>;
export const attendanceLabel = {pending:'Sin responder',confirmed:'Confirmado',declined:'No viene'};
export const kindLabel = {adult:'Adulto',child:'Niño/a',baby:'Bebé',unknown:'Sin definir'};

function parseRows(source:string) {
  const delimiter=source.includes('\t')?'\t':',';
  const rows:string[][]=[]; let row:string[]=[];let cell='';let quote=false;
  for(let i=0;i<source.length;i++) {const c=source[i];if(c==='"'){if(quote&&source[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(!quote&&c===delimiter){row.push(cell.trim());cell='';}else if(!quote&&c==='\n'){row.push(cell.trim());rows.push(row);row=[];cell='';}else if(c!=='\r')cell+=c;}
  if(quote)throw new Error('Hay comillas sin cerrar en el archivo.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows.filter(r=>r.some(Boolean));
}
export function GuestManager({event,mutate,busy,invitation,setInvitation}:{event:EventView;mutate:Mutate;busy:boolean;invitation:{groupId:string;token:string}|null;setInvitation:(value:null)=>void}) {
  const [label,setLabel]=useState('');const [names,setNames]=useState('');const [search,setSearch]=useState('');const [edit,setEdit]=useState<Person|null>(null);const [importText,setImportText]=useState('');const [error,setError]=useState('');const [editError,setEditError]=useState('');const [copied,setCopied]=useState(false);const dialogRef=useRef<HTMLDivElement>(null);const dialogOpener=useRef<HTMLElement|null>(null);const isEditing=Boolean(edit);
  useEffect(()=>{if(!isEditing)return;const opener=dialogOpener.current;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setEdit(null);if(e.key==='Tab'){const items=Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea')??[]);if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key);opener?.focus();};},[isEditing]);
  const visible=useMemo(()=>event.groups.filter(g=>`${g.label} ${event.people.filter(p=>p.groupId===g.id).map(p=>p.name).join(' ')}`.toLowerCase().includes(search.toLowerCase())),[event,search]);
  async function importGuests() {try{const rows=parseRows(importText);const header=rows.shift()?.map(x=>x.toLowerCase());if(header?.join(',')!=='grupo,nombre,tipo,necesita_asiento')throw new Error('Usá las columnas grupo,nombre,tipo,necesita_asiento.');
    const groups=new Map<string,{label:string;people:{name:string;kind:string;seatRequired:boolean}[]}>();
    for(const [i,r] of rows.entries()){if(r.length!==4||!r[0]||!['adulto','niño','bebe','bebé','sin definir'].includes(r[2].toLowerCase())||!['si','sí','no'].includes(r[3].toLowerCase()))throw new Error(`Revisá la fila ${i+2}: grupo, tipo y asiento son obligatorios.`); const [group,name,kind,seat]=r; if(!groups.has(group))groups.set(group,{label:group,people:[]}); groups.get(group)!.people.push({name,kind:({'adulto':'adult','niño':'child','bebe':'baby','bebé':'baby','sin definir':'unknown'} as Record<string,string>)[kind.toLowerCase()],seatRequired:seat.toLowerCase()!=='no'});}
    if(!groups.size)throw new Error('La lista no tiene personas para agregar.');
    if(await mutate('group_import',{groups:[...groups.values()]})){setImportText('');setError('');}
  }catch(e){setError((e as Error).message);}}
  const invitationUrl=invitation&&typeof window!=='undefined'?`${window.location.origin}/invitacion/${event.id}#i=${invitation.token}`:'';
  return <><div className={styles.grid}><section className={styles.card}><h2>Invitar a una persona o familia</h2><p>Una invitación reúne a sus integrantes. Cada persona conserva su lugar en la lista, aunque después se siente en otra mesa.</p><form className={styles.form} onSubmit={async e=>{e.preventDefault();const people=names.split('\n').map(n=>n.trim()).filter(Boolean).map(name=>({name:name==='?'?'':name,kind:'unknown',seatRequired:true}));if(!people.length){setError('Agregá al menos una persona.');return;}if(await mutate('group_add',{label,people})){setLabel('');setNames('');setError('');}}}><label className={styles.field}>Nombre de la invitación<input required maxLength={100} placeholder="Familia Ríos" value={label} onChange={e=>setLabel(e.target.value)}/></label><label className={styles.field}>Integrantes, uno por renglón<textarea required value={names} onChange={e=>setNames(e.target.value)} placeholder={'Camila Ríos\nJulián Ríos\n?'} /><small>Usá ? para un acompañante cuyo nombre todavía no conocen.</small></label><button className={styles.button} disabled={busy}><Plus size={16}/> Agregar invitación</button></form></section>
  <section className={styles.card}><h2>Traer una lista</h2><p>Importá un CSV o pegá las cuatro columnas desde una planilla. Las personas con el mismo nombre siguen siendo personas distintas. La importación agrega grupos; no reemplaza los existentes.</p><div className={styles.form}><button className={styles.secondary} onClick={()=>downloadFile('grupo,nombre,tipo,necesita_asiento\nFamilia de ejemplo,Persona de ejemplo,adulto,sí\nFamilia de ejemplo,,bebé,no\n','modelo-invitados.csv','text/csv;charset=utf-8')}>Descargar modelo CSV</button><label className={styles.field}>Archivo de invitados<input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>500_000){setError('La planilla supera 500 KB.');return;}setImportText(await f.text());}}}/></label><label className={styles.field}>O pegá las columnas<textarea value={importText} onChange={e=>setImportText(e.target.value)} placeholder="grupo,nombre,tipo,necesita_asiento"/></label><button disabled={busy||!importText.trim()} className={styles.secondary} onClick={importGuests}>Revisar e incorporar lista</button></div></section></div>
  {error&&<p role="alert" className={styles.error} style={{marginTop:20}}>{error}</p>}
  {invitation&&<section className={styles.card} style={{marginTop:24}}><h2>El enlace de esta invitación</h2><p>Permite ver y corregir las respuestas de este grupo. Compartilo sólo con sus integrantes. Al generar uno nuevo, el anterior deja de funcionar.</p><div className={styles.secret}>{invitationUrl}</div><div className={styles.actions}><button className={styles.button} onClick={async()=>{try{await navigator.clipboard.writeText(invitationUrl);setCopied(true);}catch{setError('No pudimos copiar. Seleccioná el enlace y copialo manualmente.');}}}><Copy size={16}/>{copied?'Enlace copiado':'Copiar enlace'}</button><a className={styles.secondary} target="_blank" rel="noreferrer" href={invitationUrl}>Ver invitación</a><button className={styles.secondary} onClick={()=>{setInvitation(null);setCopied(false);}}>Cerrar enlace</button></div></section>}
  <section className={styles.card} style={{marginTop:24}}><div className={styles.toolbar}><h2>Sus invitados <span className={styles.badge}>{event.people.length} personas</span></h2><button className={styles.secondary} onClick={async()=>{try{const r=await fetch(`/api/boda-studio/events/${event.id}/export?target=guests`,{cache:'no-store'});if(!r.ok)throw new Error('No pudimos descargar la lista. Actualizá el panel e intentá nuevamente.');downloadFile(await r.text(),'invitados-y-respuestas.csv','text/csv;charset=utf-8');}catch(e){setError((e as Error).message);}}}>Descargar invitados y respuestas</button><input className={styles.search} aria-label="Buscar invitados" placeholder="Buscar una persona o familia" value={search} onChange={e=>setSearch(e.target.value)}/></div>
  {!visible.length?<div className={styles.empty}>{search?'No encontramos coincidencias.':'La lista empieza con la primera invitación.'}</div>:visible.map(g=><div key={g.id} className={styles.person}><div className={styles.toolbar}><strong>{g.label}</strong><button className={styles.secondary} disabled={busy||!event.published} onClick={()=>{if(g.invitationVersion>0&&!window.confirm('El enlace anterior dejará de funcionar. ¿Generar uno nuevo para este grupo?'))return;mutate('invitation_rotate',{groupId:g.id});}}><RefreshCw size={14}/>{g.invitationVersion?'Renovar enlace':'Crear enlace'}</button></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Persona</th><th>Respuesta</th><th>Asiento</th><th>Menú</th><th><span className={styles.muted}>Editar</span></th></tr></thead><tbody>{event.people.filter(p=>p.groupId===g.id).map(p=><tr key={p.id}><td>{p.name||'Acompañante sin nombre'}<small className={styles.muted} style={{display:'block'}}>{kindLabel[p.kind]}</small></td><td>{attendanceLabel[p.attendance]}</td><td>{p.seatRequired?'Necesita':'Sin asiento'}</td><td>{p.menu||'Pendiente'}{Boolean(p.accessibilityNeeds?.length)&&<small className={styles.muted} style={{display:'block'}}>{p.accessibilityNeeds.map(n=>accessibilityLabels[n]).join(' · ')}</small>}{p.dietaryRestriction&&<small className={styles.muted} style={{display:'block'}}>Restricción {p.shareDietaryRestriction?'compartida con catering':'sin autorización de exportación'}</small>}</td><td><button className={styles.secondary} onClick={e=>{dialogOpener.current=e.currentTarget;setEditError('');setEdit({...p});}}>Editar persona</button></td></tr>)}</tbody></table></div></div>)}{!event.published&&<p className={styles.muted} style={{marginTop:20}}>Primero revisen y publiquen su invitación para generar los enlaces de cada familia.</p>}</section>
  {edit&&<div className={styles.modal}><section ref={dialogRef} className={styles.dialog} role="dialog" aria-modal="true" aria-label="Editar persona"><h2>Datos de esta persona</h2><form className={styles.form} onSubmit={async e=>{e.preventDefault();const {id,name,kind,seatRequired,attendance,menu,note,dietaryRestriction,shareDietaryRestriction,accessibilityNeeds}=edit;if(await mutate('person_update',{personId:id,name,kind,seatRequired,attendance,menu,note,dietaryRestriction,shareDietaryRestriction,accessibilityNeeds})){setEdit(null);setEditError('');}else setEditError('No se guardó y tus cambios siguen aquí. Si ahora necesita una plaza, comprobá que su mesa tenga capacidad. Si los datos cambiaron en otro dispositivo, cerrá este formulario y actualizá el panel antes de reintentar.');}}><label className={styles.field}>Nombre<input autoFocus maxLength={100} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><div className={styles.fields}><label className={styles.field}>Asistencia<select value={edit.attendance} onChange={e=>setEdit({...edit,attendance:e.target.value as Person['attendance']})}>{Object.entries(attendanceLabel).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label className={styles.field}>Tipo<select value={edit.kind} onChange={e=>setEdit({...edit,kind:e.target.value as Person['kind']})}>{Object.entries(kindLabel).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div><PersonSupportFields person={edit} onChange={setEdit} disabled={busy}/><label className={styles.field}>Nota privada de la pareja<textarea maxLength={300} value={edit.note} onChange={e=>setEdit({...edit,note:e.target.value})}/><small>No se muestra a invitados ni se incluye en las listas exportadas.</small></label><div role="status" aria-live="polite">{editError&&<p className={styles.error} role="alert">{editError}</p>}</div><div className={styles.actions}><button disabled={busy} className={styles.button}>Guardar persona</button><button type="button" className={styles.secondary} onClick={()=>setEdit(null)}>Cancelar</button></div></form></section></div>}
  </>;
}
