"use client";
import { useEffect, useRef, useState } from 'react';
import { Check, X } from 'lucide-react';
import type { Group, Person } from '@/lib/boda-service/types';
import type { WeddingTrialWorkspace } from '@/lib/boda-trial/schema';
import { InvitationPreview } from '@/components/boda-commercial/InvitationPreview';
import { studioRequest } from './client';
import { PersonSupportFields } from './PersonSupportFields';
import styles from './studio.module.css';
type PublicWedding={id:string;revision:number;workspace:WeddingTrialWorkspace;photos:string[];rsvpClosed?:boolean};
type ResponseView={group:Group;people:Person[];revision:number;rsvpClosed?:boolean};
export function PublishedWedding({eventId}:{eventId:string}) {
 const [wedding,setWedding]=useState<PublicWedding|null>(null);const [group,setGroup]=useState<ResponseView|null>(null);const [people,setPeople]=useState<Person[]>([]);const [token,setToken]=useState('');const [error,setError]=useState('');const [responseError,setResponseError]=useState('');const [ready,setReady]=useState(false);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);const modalRef=useRef<HTMLDivElement>(null);const openerRef=useRef<HTMLElement|null>(null);
 useEffect(()=>{let alive=true;async function load(){try{const pub=await studioRequest<PublicWedding>(`/public/${eventId}`);if(!alive)return;setWedding(pub);const fragment=new URLSearchParams(window.location.hash.slice(1));const key=fragment.get('i')??'';setToken(key);if(key){try{const result=await studioRequest<ResponseView>(`/rsvp/${eventId}`,{token:key,action:'get'});if(alive){setGroup(result);setPeople(result.people);}}catch(e){if(alive)setResponseError((e as Error).message);}}}catch(e){if(alive)setError((e as Error).message);}finally{if(alive)setReady(true);}}load();return()=>{alive=false;};},[eventId]);
 useEffect(()=>{if(!open)return;openerRef.current=document.activeElement as HTMLElement;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const timer=window.setTimeout(()=>modalRef.current?.querySelector<HTMLElement>('button,input,select')?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const list=Array.from(modalRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')??[]);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{window.clearTimeout(timer);document.body.style.overflow=previous;document.removeEventListener('keydown',key);openerRef.current?.focus();};},[open]);
 async function reloadResponse(){try{const x=await studioRequest<ResponseView>(`/rsvp/${eventId}`,{token,action:'get'});setGroup(x);setPeople(x.people);setResponseError('');setSaved(false);}catch(e){setResponseError((e as Error).message);}}
 async function submit(){if(!group)return;setBusy(true);setResponseError('');try{const x=await studioRequest<ResponseView>(`/rsvp/${eventId}`,{token,action:'submit',revision:group.revision,people:people.map(({id,name,attendance,seatRequired,menu,kind,dietaryRestriction,shareDietaryRestriction,accessibilityNeeds})=>({id,name,attendance,seatRequired,menu,kind,dietaryRestriction,shareDietaryRestriction,accessibilityNeeds}))});setGroup(x);setPeople(x.people);setSaved(true);}catch(e){setResponseError((e as Error).message);}finally{setBusy(false);}}
 const closed=group?.rsvpClosed??wedding?.rsvpClosed??false;
 return <div className={styles.page}>{!wedding?<main className={styles.gate}><p className={styles.eyebrow}>Una invitación especial</p><h1>{!ready?'Abriendo la invitación…':'Esta invitación no está disponible.'}</h1><p>{error?'Pedile a la pareja el enlace actualizado. Puede que estén preparando una nueva versión.':'En un momento vas a poder ver todos los detalles.'}</p></main>:<><InvitationPreview workspace={wedding.workspace} photoUrls={wedding.photos} mode="published" guestLabel={group?.group.label} guestCount={group?.people.length} onRsvpClick={()=>setOpen(true)}/>
 {open&&<div className={styles.modal} onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><section ref={modalRef} className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="rsvp-title"><div className={styles.toolbar}><p className={styles.eyebrow}>Nos encantaría verte</p><button type="button" className={styles.secondary} aria-label="Cerrar confirmación" onClick={()=>setOpen(false)}><X size={17}/></button></div><h2 id="rsvp-title">{saved?'Gracias por responder.':'¿Nos acompañás?'}</h2>
 {saved?<><div role="status" className={styles.notice}><Check size={20}/><div>Tu respuesta quedó guardada para {group?.group.label}.<br/>{people.filter(p=>p.attendance==='confirmed').length} personas confirmadas.{people.some(p=>p.attendance==='pending')&&<><br/>{people.filter(p=>p.attendance==='pending').length} todavía por confirmar.</>}</div></div><p className={styles.muted}>Si cambia algo, podés volver a este enlace mientras las confirmaciones estén abiertas.</p><button className={styles.secondary} onClick={()=>setSaved(false)}>Revisar mi respuesta</button></>:!group?<><p>{token?'El enlace de confirmación necesita actualizarse. Pedile uno nuevo a la pareja.':'Para confirmar necesitás el enlace personal que te compartió la pareja. Este enlace permite ver la invitación.'}</p>{responseError&&<p className={styles.error} role="alert">{responseError}</p>}</>:<form className={styles.form} onSubmit={e=>{e.preventDefault();submit();}}><p className={styles.muted}>{group.group.label} · {group.people.length} {group.people.length===1?'persona invitada':'personas invitadas'}. Respondé por cada integrante para que la pareja pueda organizar sus lugares.</p>{closed&&<div className={styles.notice}>Las confirmaciones están cerradas. Para un cambio, contactá a la pareja.</div>}
 {people.map((person,index)=><fieldset disabled={busy||closed} className={styles.person} key={person.id} style={{borderRight:0,borderLeft:0,borderBottom:0,margin:0}}><legend>{person.name||`Acompañante ${index+1}`}</legend><div className={styles.form}><label className={styles.field}>Nombre y apellido (puede quedar pendiente)<input maxLength={100}  value={person.name} onChange={e=>setPeople(people.map(p=>p.id===person.id?{...p,name:e.target.value}:p))}/></label><label className={styles.field}>¿Va a venir?<select required value={person.attendance} onChange={e=>setPeople(people.map(p=>p.id===person.id?{...p,attendance:e.target.value as Person['attendance']}:p))}><option value="pending">Todavía no sé</option><option value="confirmed">Sí, va a estar</option><option value="declined">No va a poder ir</option></select></label>{person.attendance==='confirmed'&&<PersonSupportFields person={person} onChange={next=>setPeople(people.map(p=>p.id===person.id?next:p))}/>}</div></fieldset>)}
 {responseError&&<div role="alert" className={styles.error}>{responseError}<button type="button" className={styles.secondary} onClick={reloadResponse}>Traer la última respuesta</button></div>}<p className={styles.muted}>La pareja recibe estas respuestas. El menú se incluye en la lista para catering; las restricciones sólo si autorizás compartirlas. Las necesidades para preparar el lugar se incluyen en la lista para el salón. Podés corregir o retirar información desde este enlace mientras las confirmaciones estén abiertas; después, contactá a la pareja.</p><button className={styles.button} disabled={busy||closed}>{busy?'Guardando respuesta…':'Guardar confirmación'}</button></form>}</section></div>}
 </>}</div>;
}
