"use client";
import { useCallback, useRef, useState } from 'react';
import { ArrowRight, Download, Plus, X } from 'lucide-react';
import type { EventView } from '@/lib/boda-service/types';
import type { Mutate } from './GuestManager';
import styles from './studio.module.css';
import { SeatingSuggestions } from './SeatingSuggestions';
import { placeBreakdown } from '@/lib/boda-service/seating-suggestions';
import { FloorPlanEditor, type FloorPlanHandle } from './FloorPlanEditor';
export function TablePlanner({event,mutate,busy,onUnsavedChange}:{event:EventView;mutate:Mutate;busy:boolean;onUnsavedChange?:(dirty:boolean)=>void}) {
  const [layoutDirty,setLayoutDirty]=useState(false);const floorRef=useRef<FloorPlanHandle>(null);
  const handleLayoutDirty=useCallback((dirty:boolean)=>{setLayoutDirty(dirty);onUnsavedChange?.(dirty);},[onUnsavedChange]);
  const [name,setName]=useState('');const [capacity,setCapacity]=useState(8);const [selected,setSelected]=useState<string[]>([]);const [target,setTarget]=useState('');const [onlyUnassigned,setOnlyUnassigned]=useState(true);const [error,setError]=useState('');
  const confirmed=event.people.filter(p=>p.attendance==='confirmed');
  const seated=new Set(event.assignments.map(a=>a.personId));
  const unassigned=confirmed.filter(p=>p.seatRequired&&!seated.has(p.id));
  const visible=confirmed.filter(p=>(!onlyUnassigned||!seated.has(p.id)));
  const selectedVisible=selected.filter(id=>visible.some(person=>person.id===id));
  const missingNames=confirmed.filter(p=>p.namePending);
  async function exportList(kind:string) {try{const response=await fetch(`/api/boda-studio/events/${event.id}/export?target=${kind}`,{cache:'no-store'});if(!response.ok){const x=await response.json();throw new Error(x.message||x.error||'Revisá las asignaciones antes de exportar.');}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`boda-${kind}-revision-${event.revision}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setError('');}catch(e){setError((e as Error).message);}}
  return <><div className={styles.notice}>Las mesas se organizan con las personas confirmadas. Un bebé en brazos puede contar como asistente sin ocupar un asiento. Ustedes deciden cómo repartir a cada familia.</div>
  <div className={styles.metrics}><div className={styles.metric}><strong>{confirmed.length}</strong><span>personas confirmadas</span></div><div className={styles.metric}><strong>{confirmed.filter(p=>p.seatRequired).length}</strong><span>lugares necesarios</span></div><div className={styles.metric}><strong>{unassigned.length}</strong><span>personas por ubicar</span></div><div className={styles.metric}><strong>{event.tables.reduce((sum,t)=>sum+t.capacity,0)}</strong><span>capacidad total</span></div></div>
  <FloorPlanEditor ref={floorRef} event={event} mutate={mutate} busy={busy} onUnsavedChange={handleLayoutDirty}/>
  <div className={styles.noPrint}>{layoutDirty&&<p className={styles.notice}>Guarden o descarten los cambios del plano antes de asignar personas o modificar la lista de mesas.</p>}</div>
  <SeatingSuggestions event={event} mutate={mutate} busy={busy} layoutDirty={layoutDirty}/>
  <div className={`${styles.grid} ${styles.noPrint}`}><section className={styles.card}><h2>Personas por ubicar</h2><label className={styles.check}><input type="checkbox" checked={onlyUnassigned} onChange={e=>{setOnlyUnassigned(e.target.checked);setSelected([]);}}/> Mostrar sólo quienes no tienen mesa</label>
    {!visible.length?<div className={styles.empty}>{confirmed.length?'Todas las personas que necesitan asiento ya tienen mesa.':'Las confirmaciones aparecerán acá para que puedan ubicarlas.'}</div>:<div style={{maxHeight:380,overflowY:'auto'}}>{event.groups.filter(g=>visible.some(p=>p.groupId===g.id)).map(g=><div key={g.id} className={styles.person}><label className={styles.check}><input type="checkbox" aria-label={`Seleccionar ${g.label}`} checked={visible.filter(p=>p.groupId===g.id).every(p=>selected.includes(p.id))} onChange={e=>{const ids=visible.filter(p=>p.groupId===g.id).map(p=>p.id);setSelected(e.target.checked?[...new Set([...selected,...ids])]:selected.filter(id=>!ids.includes(id)));}}/><strong>{g.label}</strong></label>{visible.filter(p=>p.groupId===g.id).map(p=><label key={p.id} className={styles.check} style={{paddingLeft:24}}><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/>{p.name||'Acompañante sin nombre'}{!p.seatRequired&&<small className={styles.muted}>Sin asiento</small>}{seated.has(p.id)&&<span className={styles.badge}>{event.tables.find(t=>event.assignments.some(a=>a.personId===p.id&&a.tableId===t.id))?.name}</span>}</label>)}</div>)}</div>}
    <div className={styles.form} style={{marginTop:22}}><label className={styles.field}>Llevar {selectedVisible.length||'las'} personas seleccionadas a<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Elegir mesa</option>{event.tables.map(t=><option key={t.id} value={t.id}>{t.name} · {event.assignments.filter(a=>a.tableId===t.id&&event.people.find(p=>p.id===a.personId)?.seatRequired).length}/{t.capacity}</option>)}</select></label><button className={styles.button} disabled={busy||layoutDirty||!selectedVisible.length||!target} onClick={async()=>{if(!layoutDirty&&await mutate('assign',{personIds:selectedVisible,tableId:target}))setSelected([]);}}>Asignar a esta mesa <ArrowRight size={16}/></button></div></section>
    <section className={styles.card}><h2>Agregar una mesa</h2><form className={styles.form} onSubmit={async e=>{e.preventDefault();if(!layoutDirty&&await mutate('table_add',{name,capacity}))setName('');}}><label className={styles.field}>Nombre o número<input required maxLength={60} placeholder="Mesa 1" value={name} onChange={e=>setName(e.target.value)}/></label><label className={styles.field}>Cantidad de lugares<input type="number" required min={1} max={100} value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><button className={styles.secondary} disabled={busy||layoutDirty}><Plus size={16}/> Agregar mesa</button></form><hr style={{border:0,borderTop:'1px solid #d8dfd5',margin:'28px 0'}}/><h3>Cerrar la distribución</h3><p>{unassigned.length?`Quedan ${unassigned.length} personas que necesitan mesa.`:'No quedan personas que necesiten mesa sin asignar.'} {missingNames.length?`Hay ${missingNames.length} acompañantes pendientes de nombre.`:''}</p><p>Revisen nombres, capacidades y cambios de asistencia antes de entregar la lista. Cualquier cambio posterior exige una nueva revisión.</p><div className={styles.actions}><button disabled={busy||layoutDirty||!confirmed.length||unassigned.length>0||missingNames.length>0} className={styles.button} onClick={()=>mutate('review',{ready:true})}>Marcar distribución revisada</button></div></section></div>
  {error&&<div role="alert" className={styles.error}>{error}</div>}
  <div className={styles.toolbar} style={{marginTop:32}}><div><h2 style={{fontFamily:'Georgia,serif',fontWeight:400}}>La distribución de sus mesas</h2><span className={styles.badge}>{event.review==='ready'?'Distribución revisada':'Pendiente de revisión'}</span></div><div className={styles.actions}><button className={styles.secondary} disabled={layoutDirty||event.review!=='ready'} onClick={()=>exportList('venue')}><Download size={15}/> Lista para el salón</button><button className={styles.secondary} disabled={layoutDirty||event.review!=='ready'} onClick={()=>exportList('catering')}>Lista para catering</button><button className={styles.secondary} disabled={layoutDirty||event.review!=='ready'} onClick={()=>window.print()}>Imprimir mesas</button></div></div>
  <div className={styles.printOnly}>{layoutDirty?'Plano sin guardar; listas de la versión guardada':event.review==='ready'?'Distribución revisada':'Pendiente de revisión'} · {new Date(event.updatedAt).toLocaleString('es-AR')} · Revisión {event.revision}</div>
  {!event.tables.length?<div className={styles.empty}>Agreguen una mesa y empiecen a ubicar a sus invitados.</div>:<div className={styles.tableCards}>{event.tables.map(t=>{const assignments=event.assignments.filter(a=>a.tableId===t.id);const usedSeats=assignments.filter(a=>event.people.find(p=>p.id===a.personId)?.seatRequired).length;return <article key={t.id} className={styles.seatCard}><div className={styles.toolbar}><h3>{t.name}</h3><button className={styles.secondary} disabled={busy||layoutDirty||assignments.length>0} onClick={()=>{if(window.confirm(`¿Eliminar ${t.name}?`))mutate('table_delete',{tableId:t.id});}} aria-label={`Eliminar ${t.name}`}><X size={15}/></button></div><div className={styles.capacity} aria-label={`${usedSeats} de ${t.capacity} lugares ocupados`}>{usedSeats} / {t.capacity}</div><button type="button" className={styles.secondary} disabled={busy} onClick={()=>floorRef.current?.selectTable(t.id)} aria-label={`Editar lugares de ${t.name}`}>Cambiar lugares y ubicación</button><p className={styles.muted} style={{fontSize:12,lineHeight:1.6,margin:'16px 0'}}>{(()=>{const p=placeBreakdown(assignments.map(a=>event.people.find(person=>person.id===a.personId)!).filter(Boolean));return `${p.ordinaryChairs} ${p.ordinaryChairs===1?'silla común':'sillas comunes'} · ${p.highchairs} ${p.highchairs===1?'alta':'altas'} · ${p.wheelchairs} ${p.wheelchairs===1?'espacio':'espacios'} para silla de ruedas`;})()}</p><ul>{assignments.map(a=>{const p=event.people.find(p=>p.id===a.personId);return <li key={a.personId}><span>{p?.name||'Acompañante sin nombre'}</span><button disabled={busy||layoutDirty} aria-label={`Quitar a ${p?.name||'acompañante'} de ${t.name}`} onClick={()=>mutate('assign',{personIds:[a.personId],tableId:null})}><X size={14}/></button></li>;})}</ul>{!assignments.length&&<p className={styles.muted} style={{textAlign:'center',marginTop:16}}>Todavía sin invitados</p>}</article>;})}</div>}
  </>;
}
