"use client";
import Image from 'next/image';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, Check, Eye, RefreshCw, Save, X } from 'lucide-react';
import type { EventView } from '@/lib/boda-service/types';
import type { TrialContent, WeddingThemeId, WeddingTrialWorkspace } from '@/lib/boda-trial/schema';
import { getWeddingTheme, resolveWeddingTrialDesign, WEDDING_THEMES, WEDDING_THEME_PRESETS } from '@/lib/boda-trial/themes';
import { InvitationPreview } from '@/components/boda-commercial/InvitationPreview';
import { WeddingDesignControls } from '@/components/boda-commercial/WeddingDesignControls';
import { GuestManager } from './GuestManager';
import { TablePlanner } from './TablePlanner';
import {WeddingAccessGate} from './WeddingAccessGate';
import {WeddingRecoveryControls} from './WeddingRecoveryControls';
import {WeddingDeleteControls} from './WeddingDeleteControls';
import {rememberWedding} from './access-receipt';
import { preparePhoto, studioRequest } from './client';
import styles from './studio.module.css';
type Tab='summary'|'invitation'|'guests'|'tables'|'operation';
function designFingerprint(w:WeddingTrialWorkspace){return JSON.stringify({content:w.content,design:w.design,themeId:w.event.themeId});}
const tabs:{id:Tab;label:string}[]=[{id:'summary',label:'Resumen'},{id:'invitation',label:'Invitación'},{id:'guests',label:'Invitados'},{id:'tables',label:'Mesas'},{id:'operation',label:'Actividad y copias'}];
const contentFields:{key:keyof Omit<TrialContent,'eventId'>;label:string;type?:string;long?:boolean}[]=[{key:'partnerOne',label:'Nombre de la primera persona'},{key:'partnerTwo',label:'Nombre de la segunda persona'},{key:'date',label:'Fecha de la boda',type:'date'},{key:'dressCode',label:'Cómo vestirse'},{key:'ceremonyLocation',label:'Lugar de la ceremonia'},{key:'ceremonyTime',label:'Hora de la ceremonia',type:'time'},{key:'ceremonyAddress',label:'Dirección de la ceremonia'},{key:'celebrationLocation',label:'Lugar de la celebración'},{key:'celebrationTime',label:'Hora de la celebración',type:'time'},{key:'celebrationAddress',label:'Dirección de la celebración'},{key:'message',label:'Mensaje de bienvenida',long:true},{key:'story',label:'Su historia',long:true}];

export function WeddingStudio({eventId}:{eventId:string}) {
 const [event,setEvent]=useState<EventView|null>(null);const [deleted,setDeleted]=useState(false);const [draft,setDraft]=useState<WeddingTrialWorkspace|null>(null);const [tab,setTab]=useState<Tab>('summary');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [preview,setPreview]=useState(false);const [dirty,setDirty]=useState(false);const [layoutDirty,setLayoutDirty]=useState(false);const [accessPending,setAccessPending]=useState(false);const [invitation,setInvitation]=useState<{groupId:string;token:string}|null>(null);const [minutes,setMinutes]=useState(15);const [reference,setReference]=useState('');const [amount,setAmount]=useState('');const [newPassword,setNewPassword]=useState('');const [draftBase,setDraftBase]=useState('');const previewRef=useRef<HTMLDivElement>(null);const previewButton=useRef<HTMLButtonElement>(null);
 const refresh=useCallback(async(resetDraft=true)=>{const result=await studioRequest<{event:EventView}>(`/events/${eventId}`);setEvent(result.event);if(resetDraft){setDraft(result.event.draft);setDraftBase(designFingerprint(result.event.draft));setDirty(false);}return result.event;},[eventId]);
 useEffect(()=>{let alive=true;studioRequest<{event:EventView}>(`/events/${eventId}`).then(x=>{if(alive){rememberWedding(x.event.id);setEvent(x.event);setDraft(x.event.draft);setDraftBase(designFingerprint(x.event.draft));}}).catch(()=>undefined).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[eventId]);
 const onLayoutDirty=useCallback((next:boolean)=>setLayoutDirty(next),[]);
 function chooseTab(next:Tab){if(busy||next===tab)return;if(accessPending&&!window.confirm('Todavía no guardaron la clave de recuperación. ¿Cambiar de sección igualmente?'))return;if(layoutDirty&&!window.confirm('El plano tiene cambios sin guardar. ¿Descartarlos y cambiar de sección?'))return;setTab(next);}
 useEffect(()=>{if(!dirty&&!layoutDirty&&!accessPending)return;const before=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty,layoutDirty,accessPending]);
 async function mutate(action:string,payload:Record<string,unknown>={}){if(!event||busy)return false;if(action==='content'&&designFingerprint(event.draft)!==draftBase){setError('El diseño cambió en otro dispositivo. Revisá las dos versiones antes de guardar.');return false;}setBusy(true);setError('');setMessage('');try{const result=await studioRequest<{event:EventView;invitationToken?:string}>(`/events/${eventId}`,{revision:event.revision,action,...payload},'PATCH');setEvent(result.event);if(action==='content'||action==='rollback'){setDraft(result.event.draft);setDraftBase(designFingerprint(result.event.draft));setDirty(false);}if(result.invitationToken)setInvitation({groupId:String(payload.groupId),token:result.invitationToken});setMessage(action==='publish'?'La versión revisada ya está disponible en el enlace de la invitación.':action==='content'?'Los cambios quedaron guardados en el borrador.':action==='review'?'La distribución quedó marcada como revisada. Si cambia la lista, deberán revisarla otra vez.':'Cambios guardados.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 function editContent(key:keyof TrialContent,value:string){if(draft){setDraft({...draft,content:{...draft.content,[key]:value}});setDirty(true);}}
 function chooseTheme(themeId:WeddingThemeId){if(draft){setDraft({...draft,event:{...draft.event,themeId},design:resolveWeddingTrialDesign(themeId,{...draft.design,...WEDDING_THEME_PRESETS[themeId]})});setDirty(true);}}
 async function photos(files:FileList|null){if(!files||!event)return;setError('');setBusy(true);try{if(event.photos.length+files.length>6)throw new Error('Podés guardar hasta seis fotos. Quitá alguna antes de agregar otra.');const prepared=await Promise.all(Array.from(files).map(preparePhoto));setBusy(false);await mutatePhotos([...event.photos,...prepared]);}catch(e){setError((e as Error).message);setBusy(false);}}
 async function mutatePhotos(next:string[]){if(!event)return;setBusy(true);try{const x=await studioRequest<{event:EventView}>(`/events/${eventId}`,{revision:event.revision,action:'photos',photos:next},'PATCH');setEvent(x.event);setMessage('Fotos guardadas. Revisá la invitación antes de publicar una nueva versión.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function backup(){setError('');try{const r=await fetch(`/api/boda-studio/events/${eventId}/backup`,{cache:'no-store'});if(!r.ok)throw new Error('No pudimos preparar la copia. Ingresá nuevamente si tu sesión venció.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`boda-copia-${eventId}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(preview){const frame=requestAnimationFrame(()=>previewRef.current?.scrollIntoView({behavior:'instant',block:'start'}));return()=>cancelAnimationFrame(frame);}},[preview]);
 const draftConflict=Boolean(dirty&&event&&draftBase&&designFingerprint(event.draft)!==draftBase);
 const confirmed=event?.people.filter(p=>p.attendance==='confirmed')??[];
 return <div className={styles.page}><header className={styles.topbar}><Link href="/boda" prefetch={false} className={styles.brand} onClick={e=>{if((dirty||layoutDirty||accessPending)&&!window.confirm("Hay cambios o una clave de recuperación sin guardar. ¿Salir del panel?"))e.preventDefault();}}>SODI <span>Bodas</span></Link><small>Su invitación y sus invitados, en un solo lugar</small>{event&&<button className={styles.secondary} disabled={busy} onClick={async()=>{if((dirty||layoutDirty||accessPending)&&!window.confirm('Hay cambios o una clave de recuperación sin guardar. ¿Cerrar sesión?'))return;await studioRequest(`/events/${eventId}/logout`,{});setEvent(null);setDraft(null);setDirty(false);setLayoutDirty(false);}}>Cerrar sesión</button>}</header>
 {deleted?<main className={styles.gate}><h1>La boda quedó eliminada.</h1><p>Su contenido ya no está disponible en SODI y los enlaces dejaron de funcionar.</p><Link className={styles.button} href="/boda">Volver a SODI Bodas</Link></main>:!event||!draft?<main className={styles.gate}><p className={styles.eyebrow}>Su espacio privado</p><h1>Todo para su gran día.</h1><p>Ingresen con la contraseña de esta boda para continuar con la invitación y organizar a sus invitados.</p>{loading?<div className={styles.notice}>Abriendo su espacio…</div>:<WeddingAccessGate eventId={eventId} onAuthenticated={next=>{setEvent(next);setDraft(next.draft);setDraftBase(designFingerprint(next.draft));setError('');}}/>}</main>:
 <main className={styles.main}><header className={styles.hero}><div><p className={styles.eyebrow}>{event.draft.content.date?new Date(`${event.draft.content.date}T12:00:00`).toLocaleDateString('es-AR',{day:'numeric',month:'long',year:'numeric'}):'Su próxima celebración'}</p><h1>{event.draft.content.partnerOne} <i>y</i> {event.draft.content.partnerTwo}</h1><p>Una invitación para encontrarse. Una lista para llegar tranquilos.</p></div><div className={styles.actions}><span className={styles.badge}>{event.published?'Invitación publicada':'Invitación en borrador'}</span><button className={styles.secondary} disabled={busy} onClick={()=>refresh(!dirty).then(()=>setMessage(dirty?'Respuestas actualizadas. Conservamos tus cambios de diseño sin guardar.':'Panel actualizado.')).catch(e=>setError(e.message))}><RefreshCw size={15}/>Actualizar</button></div></header>
 <nav className={styles.tabs} aria-label="Secciones de su boda">{tabs.map(t=><button key={t.id} aria-pressed={tab===t.id} disabled={busy} onClick={()=>chooseTab(t.id)}>{t.label}</button>)}</nav>
 {error&&<div role="alert" className={styles.error}>{error}</div>}{message&&<div role="status" className={styles.notice}><Check size={18}/>{message}</div>}
 {tab==='summary'&&<><div className={styles.metrics}><div className={styles.metric}><strong>{event.groups.length}</strong><span>invitaciones por familia o grupo</span></div><div className={styles.metric}><strong>{confirmed.length}</strong><span>personas confirmadas</span></div><div className={styles.metric}><strong>{event.people.filter(p=>p.attendance==='pending').length}</strong><span>personas por responder</span></div><div className={styles.metric}><strong>{confirmed.filter(p=>p.seatRequired&&!event.assignments.some(a=>a.personId===p.id)).length}</strong><span>personas que necesitan mesa</span></div></div><div className={styles.grid}><section className={styles.card}><p className={styles.eyebrow}>A su ritmo</p><h2>Los próximos pasos</h2><ol className={styles.steps}><li><div><strong>Preparen la invitación</strong><p>Sus nombres, sus fotos y los detalles del encuentro.</p><button className={styles.secondary} onClick={()=>chooseTab('invitation')}>Revisar invitación</button></div></li><li><div><strong>Armen la lista y compartan los enlaces</strong><p>Cada familia responde por las personas de su invitación.</p><button className={styles.secondary} onClick={()=>chooseTab('guests')}>Organizar invitados</button></div></li><li><div><strong>Revisen las mesas y entreguen el listado</strong><p>Una distribución con capacidades y confirmaciones al día.</p><button className={styles.secondary} onClick={()=>chooseTab('tables')}>Organizar mesas</button></div></li></ol></section><section className={styles.card}><p className={styles.eyebrow}>Lo que van a compartir</p><h2>{getWeddingTheme(event.draft.event.themeId).name}</h2><p>{event.published?'La versión publicada se mantiene hasta que decidan publicar nuevos cambios.':'Todavía nadie puede abrir la invitación. Primero revisen y publiquen una versión.'}</p><InvitationPreview workspace={event.published?.workspace??event.draft} photoUrls={event.published?.photos??event.photos} compact coverOnly startOpen mode="published" onRsvpClick={()=>chooseTab('invitation')}/><div className={styles.actions} style={{marginTop:20}}>{event.published&&<a className={styles.secondary} href={`/invitacion/${event.id}`} target="_blank" rel="noreferrer">Abrir versión publicada</a>}</div></section></div></>}
 {tab==='invitation'&&<fieldset disabled={busy} className={styles.editing}>{draftConflict&&<section className={styles.card} style={{marginBottom:24}}><h2>Hay dos versiones del diseño</h2><p>Otro dispositivo guardó cambios. Tus textos siguen acá; elegí qué versión conservar antes de publicar.</p><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Dato</th><th>Guardado en la boda</th><th>Tu borrador</th></tr></thead><tbody>{contentFields.filter(f=>draft.content[f.key]!==event.draft.content[f.key]).map(f=><tr key={f.key}><td>{f.label}</td><td>{event.draft.content[f.key]||'Vacío'}</td><td>{draft.content[f.key]||'Vacío'}</td></tr>)}<tr><td>Estilo y diseño</td><td>{getWeddingTheme(event.draft.event.themeId).name} · {event.draft.design.paletteId}</td><td>{getWeddingTheme(draft.event.themeId).name} · {draft.design.paletteId}</td></tr></tbody></table></div><div className={styles.actions} style={{marginTop:20}}><button className={styles.secondary} onClick={()=>{if(window.confirm('¿Descartar tus cambios sin guardar y usar la versión que está guardada?')){setDraft(event.draft);setDraftBase(designFingerprint(event.draft));setDirty(false);setError('');}}}>Usar la versión guardada</button><button className={styles.secondary} onClick={()=>{if(window.confirm('¿Conservar tu borrador para reemplazar la versión guardada? Revisá los campos antes de guardar.')){setDraftBase(designFingerprint(event.draft));setError('');setMessage('Conservamos tu borrador. Revisalo y pulsá Guardar borrador para reemplazar la versión anterior.');}}}>Conservar mi borrador</button></div></section>}<div className={styles.grid}><section className={styles.card}><h2>Su invitación</h2><p>Guarden el borrador y revísenlo antes de compartir. Guardar no cambia la versión que reciben los invitados.</p><form className={styles.form} onSubmit={e=>{e.preventDefault();mutate('content',{workspace:draft});}}><label className={styles.field}>Estilo<select value={draft.event.themeId} onChange={e=>chooseTheme(e.target.value as WeddingThemeId)}>{WEDDING_THEMES.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><div className={styles.fields}>{contentFields.map(f=><label key={f.key} className={styles.field} style={f.long?{gridColumn:'1 / -1'}:undefined}>{f.label}{f.long?<textarea maxLength={f.key==='story'?2000:1000} value={draft.content[f.key]??''} onChange={e=>editContent(f.key,e.target.value)}/>:<input type={f.type??'text'} maxLength={200} value={draft.content[f.key]??''} required={['partnerOne','partnerTwo','date'].includes(f.key)} onChange={e=>editContent(f.key,e.target.value)}/>}</label>)}</div><button disabled={busy||!dirty} className={styles.button}><Save size={16}/>{busy?'Guardando…':dirty?'Guardar borrador':'Borrador guardado'}</button></form></section>
 <div><section className={styles.card}><h2>Fotos de ustedes</h2><p>Hasta seis fotos. La primera abre la invitación. Se guardan con la boda para poder verla desde otros dispositivos.</p><label className={styles.field}><span>Agregar fotos JPG, PNG o WebP</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{photos(e.target.files);e.target.value='';}}/></label>{event.photos.length>0?<div className={styles.photoGrid}>{event.photos.map((p,i)=><div className={styles.photo} key={`${i}-${p.slice(-15)}`}><Image src={p} fill unoptimized alt={`Foto ${i+1} de su boda`}/><button disabled={busy} aria-label={`Quitar foto ${i+1}`} onClick={()=>mutatePhotos(event.photos.filter((_,j)=>j!==i))}><X size={15}/></button></div>)}</div>:<p className={styles.muted}>Agreguen al menos una foto propia antes de publicar. Los ejemplos de la prueba no se publican como fotos de ustedes.</p>}</section><section className={styles.card}><h2>Revisar y compartir</h2><p>La vista previa usa el mismo diseño que la invitación publicada. Primero guarden cualquier cambio pendiente.</p><div className={styles.actions}><button ref={previewButton} className={styles.secondary} onClick={()=>setPreview(!preview)}><Eye size={16}/>{preview?'Cerrar vista previa':'Ver invitación completa'}</button><button disabled={busy||dirty||!event.photos.length} className={styles.button} onClick={()=>{if(window.confirm('¿Publicar esta versión de la invitación? Quedará visible para quienes tengan el enlace.'))mutate('publish');}}>{event.published?'Publicar nueva versión':'Publicar invitación'}</button></div>{event.published&&<button className={styles.danger} style={{marginTop:18}} disabled={busy} onClick={()=>{if(window.confirm('¿Pausar la invitación? El enlace dejará de mostrarla hasta que vuelvan a publicar.'))mutate('unpublish');}}>Pausar publicación</button>}</section></div></div>
 <section className={styles.card} style={{marginTop:24}}><WeddingDesignControls design={draft.design} partnerOne={draft.content.partnerOne} partnerTwo={draft.content.partnerTwo} onChange={design=>{setDraft({...draft,design});setDirty(true);}}/><button className={styles.button} disabled={busy||!dirty} onClick={()=>mutate('content',{workspace:draft})}><Save size={16}/> Guardar diseño</button></section>{preview&&<div ref={previewRef} className={styles.preview}><div className={styles.previewBar}><button className={styles.secondary} onClick={()=>{setPreview(false);requestAnimationFrame(()=>{previewButton.current?.scrollIntoView({block:"center"});previewButton.current?.focus();});}}>Volver al diseño</button></div><InvitationPreview workspace={draft} photoUrls={event.photos} startOpen mode="published" onRsvpClick={()=>setMessage('Esta es la vista previa. Las respuestas se reciben desde el enlace de cada familia.')}/></div>}</fieldset>}
 {tab==='guests'&&<GuestManager event={event} mutate={mutate} busy={busy} invitation={invitation} setInvitation={setInvitation}/>}
 {tab==='tables'&&<TablePlanner event={event} mutate={mutate} busy={busy} onUnsavedChange={onLayoutDirty}/>}
 {tab==='operation'&&<div className={styles.grid}><div><section className={styles.card}><h2>Respuestas y acceso</h2><p>{event.rsvpClosed?'Las respuestas están cerradas. Los invitados pueden consultar su respuesta, pero no modificarla.':'Los invitados pueden confirmar o corregir su asistencia.'}</p><button className={styles.secondary} disabled={busy} onClick={()=>mutate('rsvp_close',{closed:!event.rsvpClosed})}>{event.rsvpClosed?'Reabrir confirmaciones':'Cerrar confirmaciones'}</button>{event.viewerRole==='operator'&&<form className={styles.form} style={{marginTop:24}} onSubmit={async e=>{e.preventDefault();if(await mutate('password_reset',{password:newPassword}))setNewPassword('');}}><label className={styles.field}>Restablecer contraseña (gestión SODI)<input autoComplete="new-password" type="password" minLength={12} maxLength={128} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><small>Requiere acceso de gestión. Cierra las sesiones anteriores de la pareja.</small></label><button disabled={busy} className={styles.secondary}>Restablecer acceso</button></form>}</section>
 <WeddingRecoveryControls event={event} busy={busy} onEvent={setEvent} onBusyChange={setBusy} onPendingChange={setAccessPending}/><section className={styles.card}><h2>Copias y versiones</h2><p>La copia contiene datos privados de esta boda. Guárdenla en un lugar protegido. Recuperarla vuelve a una versión anterior y requiere renovar los enlaces de invitados.</p><div className={styles.actions}><button onClick={backup} className={styles.secondary}>Descargar copia completa</button></div><label className={styles.field} style={{marginTop:18}}>Recuperar una copia<input disabled={busy} type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file||!window.confirm('¿Recuperar esta copia? Reemplaza contenido e invitados actuales y revoca accesos anteriores.'))return;setBusy(true);try{if(file.size>10_000_000)throw new Error('La copia supera el tamaño permitido.');await studioRequest(`/events/${eventId}/restore`,{revision:event.revision,backup:JSON.parse(await file.text()).backup});setMessage('Copia recuperada. Ingresá nuevamente; los enlaces de invitados deben renovarse.');setEvent(null);setDraft(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></label><ul className={styles.list}>{event.revisions.slice(-5).reverse().map(r=><li key={r.id}><div><strong>Versión guardada</strong><small>{new Date(r.at).toLocaleString('es-AR')}</small></div><button className={styles.secondary} disabled={busy||dirty} onClick={()=>{if(window.confirm('¿Volver a esta versión? También restaura la lista y las mesas de ese momento; deberán renovar los enlaces.'))mutate('rollback',{snapshotId:r.id});}}><ArrowLeft size={14}/> Recuperar</button></li>)}</ul></section><WeddingDeleteControls event={event} busy={busy} onBusyChange={setBusy} onDeleted={()=>{setEvent(null);setDraft(null);setDirty(false);setLayoutDirty(false);setAccessPending(false);setDeleted(true);}}/></div>
 <div>{event.viewerRole==='operator'&&<><section className={styles.card}><h2>Registro de trabajo</h2><p>Registrar el tiempo permite conocer el trabajo real que lleva cada boda.</p><form className={styles.form} onSubmit={async e=>{e.preventDefault();if(await mutate('ledger_add',{kind:'time',minutes,reference}))setReference('');}}><div className={styles.fields}><label className={styles.field}>Minutos<input type="number" min={1} max={1440} required value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label className={styles.field}>Tarea realizada<input required maxLength={160} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Revisión de invitación"/></label></div><button disabled={busy} className={styles.secondary}>Registrar trabajo</button></form><p style={{marginTop:20}}>Tiempo registrado: {event.ledger.reduce((s,l)=>s+(l.minutes??0),0)} minutos.</p></section><section className={styles.card}><h2>Pago verificado</h2><p>Sólo gestión SODI puede registrar un pago después de comprobarlo. Este registro no cobra dinero ni emite una factura.</p><form className={styles.form} onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);if(await mutate('ledger_add',{kind:'payment_verified',amount:Number(amount),currency:'ARS',reference:String(form.get('paymentReference'))}))setAmount('');}}><label className={styles.field}>Importe recibido en pesos<input type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className={styles.field}>Referencia del comprobante<input name="paymentReference" required maxLength={160}/></label><button disabled={busy} className={styles.secondary}>Registrar pago comprobado</button></form></section></>}<section className={styles.card}><h2>Actividad reciente</h2><ul className={styles.list}>{event.audit.slice(-10).reverse().map((a,i)=><li key={`${a.at}-${i}`}><div><strong>{({'create':'Boda creada','content':'Borrador guardado','publish':'Invitación publicada','rsvp':'Respuesta recibida','assign':'Distribución actualizada','photos':'Fotos guardadas','group_add':'Invitación agregada','group_import':'Lista incorporada','table_add':'Mesa agregada','table_update':'Mesa actualizada','room_update':'Medidas del salón guardadas','floor_feature_add':'Referencia del salón agregada','floor_feature_update':'Referencia del salón actualizada','floor_feature_delete':'Referencia del salón quitada','review':'Distribución revisada','login':'Sesión iniciada'} as Record<string,string>)[a.action]??'Actualización guardada'}</strong><small>{new Date(a.at).toLocaleString('es-AR')}</small></div></li>)}</ul></section></div></div>}
 </main>}
 </div>;
}
