"use client";
import {useState,type FormEvent} from 'react';
import {ArrowRight,KeyRound,LockKeyhole} from 'lucide-react';
import type {EventView} from '@/lib/boda-service/types';
import {studioRequest} from './client';
import {rememberWedding} from './access-receipt';
import {WeddingAccessReceipt} from './WeddingAccessReceipt';
import styles from './studio.module.css';
export function WeddingAccessGate({eventId,onAuthenticated}:{eventId:string;onAuthenticated:(event:EventView)=>void}){
 const [recovering,setRecovering]=useState(false),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [recovered,setRecovered]=useState<{event:EventView;recoveryKey:string}|null>(null),[acknowledged,setAcknowledged]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setError('');if(recovering&&password!==repeat){setError('Las contraseñas no coinciden.');return;}setBusy(true);try{if(recovering){const result=await studioRequest<{event:EventView;recoveryKey:string}>(`/events/${eventId}/recover`,{recoveryKey:key.trim(),password});rememberWedding(result.event.id);setRecovered(result);setKey('');setPassword('');setRepeat('');}else{const result=await studioRequest<{event:EventView}>(`/events/${eventId}/login`,{password});rememberWedding(result.event.id);setPassword('');onAuthenticated(result.event);}}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
 if(recovered)return <><div className={styles.notice} role="status">Acceso recuperado. La contraseña y la clave anteriores ya no sirven; las sesiones anteriores se cerraron.</div><WeddingAccessReceipt eventId={eventId} recoveryKey={recovered.recoveryKey} acknowledged={acknowledged} onAcknowledge={setAcknowledged}/><button className={styles.button} style={{marginTop:20}} disabled={!acknowledged} onClick={()=>onAuthenticated(recovered.event)}>Entrar al panel recuperado <ArrowRight size={16}/></button></>;
 return <form onSubmit={submit} className={`${styles.card} ${styles.form}`}><fieldset disabled={busy} className={styles.editing} style={{display:'grid',gap:18}}>{recovering&&<><h2>Recuperar el acceso</h2><p>Usen la clave del archivo de acceso privado que guardaron. Elegirán una contraseña nueva y recibirán otra clave.</p><label className={styles.field}>Clave de recuperación<input required autoComplete="off" spellCheck={false} maxLength={100} value={key} onChange={e=>setKey(e.target.value)}/></label></>}<label className={styles.field}>{recovering?'Nueva contraseña':'Contraseña de la boda'}<input autoComplete={recovering?'new-password':'current-password'} type="password" minLength={recovering?12:undefined} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/>{recovering&&<small>Al menos 12 caracteres. La nueva contraseña cierra las sesiones anteriores.</small>}</label>{recovering&&<label className={styles.field}>Repetí la nueva contraseña<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></label>}<button className={styles.button} disabled={busy}>{recovering?<KeyRound size={16}/>:<LockKeyhole size={16}/>} {busy?'Verificando acceso…':recovering?'Recuperar nuestra boda':'Abrir nuestro panel'}</button><button type="button" className={styles.secondary} onClick={()=>{setRecovering(!recovering);setError('');setPassword('');setRepeat('');setKey('');}}>{recovering?'Volver a ingresar con contraseña':'Olvidé la contraseña'}</button>{recovering&&<small className={styles.muted}>Si tampoco tienen la clave, consulten a quien conserva el acceso de la pareja. No recuperamos contraseñas por correo ni podemos verificar una identidad sólo por el nombre de la boda.</small>}{error&&<div className={styles.error} role="alert">{error}</div>}</fieldset></form>;
}
