// SODI Worker entry: wraps the OpenNext Cloudflare worker with the behavior Vercel provided around the app.
//  - www.sodi.com.ar -> https://sodi.com.ar (308, path and query preserved)
//  - non-production hosts (workers.dev, previews): X-Robots-Tag noindex + robots.txt Disallow: /
//  - vercel.json headers: /api/* no-store, /blog/* CDN cache-control
// Everything else (next.config redirects/headers, middleware bot filter, routes, API) is the Next app itself.
// @ts-expect-error: generated by `opennextjs-cloudflare build`
import openNext from "../.open-next/worker.js";

const PRODUCTION_HOSTS = new Set(["sodi.com.ar", "www.sodi.com.ar"]);
const APEX = "sodi.com.ar";

const BLOG_CACHE = "public, s-maxage=86400, stale-while-revalidate=604800";
const API_CACHE = "no-store, max-age=0";

export default {
  async fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> {
    const url = new URL(request.url);
    const host = url.hostname.toLowerCase();

    if (host === `www.${APEX}`) {
      return new Response(null, {
        status: 308,
        headers: { Location: `https://${APEX}${url.pathname}${url.search}` },
      });
    }

    const isProduction = PRODUCTION_HOSTS.has(host);

    if (!isProduction && url.pathname === "/robots.txt") {
      return new Response("User-agent: *\nDisallow: /\n", {
        headers: {
          "content-type": "text/plain; charset=utf-8",
          "cache-control": "public, max-age=0, must-revalidate",
          "x-robots-tag": "noindex, nofollow",
        },
      });
    }

    const upstream: Response = await openNext.fetch(request, env, ctx);
    // Vercel answers redirects with a small text/plain body and a Refresh header; Next on Workers sends them empty.
    if ([301, 302, 307, 308].includes(upstream.status) && upstream.headers.get("location") && !upstream.headers.get("content-type")) {
      const redirect = new Response("Redirecting...\n", upstream);
      redirect.headers.set("content-type", "text/plain");
      redirect.headers.set("refresh", `0;url=${upstream.headers.get("location")}`);
      if (!redirect.headers.get("cache-control")) redirect.headers.set("cache-control", "public, max-age=0, must-revalidate");
      if (!isProduction) redirect.headers.set("x-robots-tag", "noindex, nofollow");
      return redirect;
    }
    const response = new Response(upstream.body, upstream);
    // Static assets: Vercel serves .txt with an explicit charset.
    if ((response.headers.get("content-type") ?? "") === "text/plain") response.headers.set("content-type", "text/plain; charset=utf-8");

    if (url.pathname.startsWith("/api/boda-studio")) {
      // next.config.ts sets private, no-store for this path; on Vercel it wins over the vercel.json /api/* rule.
    } else if (url.pathname.startsWith("/api/")) {
      response.headers.set("cache-control", API_CACHE);
    } else if (url.pathname.startsWith("/blog/") && url.pathname.length > "/blog/".length) {
      response.headers.set("cache-control", BLOG_CACHE);
    }
    // OpenNext serves prerendered pages with s-maxage=31536000; Vercel serves them public, max-age=0, must-revalidate.
    if (/^s-maxage=31536000\b/.test(response.headers.get("cache-control") ?? "")) {
      response.headers.set("cache-control", "public, max-age=0, must-revalidate");
    }
    if (!isProduction) response.headers.set("x-robots-tag", "noindex, nofollow");
    return response;
  },
};
